org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

loader_version=0.19.5
loom_version=1.18-SNAPSHOT
mpp_version=2.2.1

mod_version=4.1.0
mod_name=Blocky Bubbles
mod_id=blocky-bubbles
mod_description=Ports the Fast Bubbles setting from Bedrock Edition!

maven_group=com.axialeaa

target_version=~26.3
build_version=26.3
modrinth_versions=26.3
fabric_api_version=0.161.0+26.3

sodium_version=0.9.3-alpha.1+mc26.3
modmenu_version=21.0.0-beta.1

modrinth_project_id=9pubtjcn
repository_url=axialeaa/BlockyBubbles